/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TimelineRouteImport } from './routes/timeline'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as EmergencyRouteImport } from './routes/emergency'
import { Route as CoachRouteImport } from './routes/coach'
import { Route as CheckinRouteImport } from './routes/checkin'
import { Route as CaregiverRouteImport } from './routes/caregiver'
import { Route as BreathingRouteImport } from './routes/breathing'
import { Route as IndexRouteImport } from './routes/index'

const TimelineRoute = TimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const EmergencyRoute = EmergencyRouteImport.update({
  id: '/emergency',
  path: '/emergency',
  getParentRoute: () => rootRouteImport,
} as any)
const CoachRoute = CoachRouteImport.update({
  id: '/coach',
  path: '/coach',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckinRoute = CheckinRouteImport.update({
  id: '/checkin',
  path: '/checkin',
  getParentRoute: () => rootRouteImport,
} as any)
const CaregiverRoute = CaregiverRouteImport.update({
  id: '/caregiver',
  path: '/caregiver',
  getParentRoute: () => rootRouteImport,
} as any)
const BreathingRoute = BreathingRouteImport.update({
  id: '/breathing',
  path: '/breathing',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/emergency': typeof EmergencyRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/emergency': typeof EmergencyRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/breathing': typeof BreathingRoute
  '/caregiver': typeof CaregiverRoute
  '/checkin': typeof CheckinRoute
  '/coach': typeof CoachRoute
  '/emergency': typeof EmergencyRoute
  '/onboarding': typeof OnboardingRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/timeline': typeof TimelineRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/breathing'
    | '/caregiver'
    | '/checkin'
    | '/coach'
    | '/emergency'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/timeline'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/breathing'
    | '/caregiver'
    | '/checkin'
    | '/coach'
    | '/emergency'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/timeline'
  id:
    | '__root__'
    | '/'
    | '/breathing'
    | '/caregiver'
    | '/checkin'
    | '/coach'
    | '/emergency'
    | '/onboarding'
    | '/resources'
    | '/settings'
    | '/timeline'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BreathingRoute: typeof BreathingRoute
  CaregiverRoute: typeof CaregiverRoute
  CheckinRoute: typeof CheckinRoute
  CoachRoute: typeof CoachRoute
  EmergencyRoute: typeof EmergencyRoute
  OnboardingRoute: typeof OnboardingRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  TimelineRoute: typeof TimelineRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/timeline': {
      id: '/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof TimelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emergency': {
      id: '/emergency'
      path: '/emergency'
      fullPath: '/emergency'
      preLoaderRoute: typeof EmergencyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/coach': {
      id: '/coach'
      path: '/coach'
      fullPath: '/coach'
      preLoaderRoute: typeof CoachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkin': {
      id: '/checkin'
      path: '/checkin'
      fullPath: '/checkin'
      preLoaderRoute: typeof CheckinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/caregiver': {
      id: '/caregiver'
      path: '/caregiver'
      fullPath: '/caregiver'
      preLoaderRoute: typeof CaregiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/breathing': {
      id: '/breathing'
      path: '/breathing'
      fullPath: '/breathing'
      preLoaderRoute: typeof BreathingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BreathingRoute: BreathingRoute,
  CaregiverRoute: CaregiverRoute,
  CheckinRoute: CheckinRoute,
  CoachRoute: CoachRoute,
  EmergencyRoute: EmergencyRoute,
  OnboardingRoute: OnboardingRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  TimelineRoute: TimelineRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
